const problemDescriptions = [
  { description: "engine making noise", cost: 600 },
  { description: "brake pads worn out", cost: 400 },
  { description: "flat tire", cost: 200 },
  { description: "oil change", cost: 120 },
  { description: "battery replacement", cost: 500 },
  { description: "alternator failure", cost: 800 },
  { description: "car overheating", cost: 750 },
  { description: "engine misfire", cost: 1000 },
  { description: "check engine light", cost: 500 },
  { description: "transmission issues", cost: 1500 },
  { description: "car not starting", cost: 600 },
  { description: "engine knocking", cost: 1200 },
  { description: "clutch slipping", cost: 800 },
  { description: "spark plugs failure", cost: 400 },
  { description: "brake fluid leak", cost: 300 },
  { description: "oil leak", cost: 450 },
  { description: "radiator leak", cost: 600 },
  { description: "fuel injector failure", cost: 700 },
  { description: "timing belt replacement", cost: 1000 },
  { description: "power steering failure", cost: 800 },
  { description: "car shaking", cost: 500 },
  { description: "air conditioning not working", cost: 600 },
  { description: "exhaust leak", cost: 400 },
  { description: "cylinder head gasket failure", cost: 1500 },
  { description: "ABS warning light", cost: 700 },
  { description: "starter motor failure", cost: 800 },
  { description: "water pump failure", cost: 900 },
  { description: "fuel pump failure", cost: 850 },
  { description: "wheel bearing failure", cost: 500 },
  { description: "battery terminal corrosion", cost: 300 },
  { description: "front suspension failure", cost: 1200 },
  { description: "rear suspension failure", cost: 1200 },
  { description: "headlight not working", cost: 250 },
  { description: "tail light not working", cost: 200 },
  { description: "fuses blown", cost: 150 },
  { description: "broken windshield", cost: 1000 },
  { description: "defroster not working", cost: 300 },
  { description: "wiper blade replacement", cost: 100 },
  { description: "engine coolant leak", cost: 550 },
  { description: "transmission fluid leak", cost: 800 },
  { description: "spark plug wire issues", cost: 400 },
  { description: "fuel tank replacement", cost: 1200 },
  { description: "car backfiring", cost: 800 },
  { description: "engine overheating warning", cost: 700 },
  { description: "battery draining quickly", cost: 400 },
  { description: "clutch pedal stuck", cost: 600 },
  { description: "radiator fan failure", cost: 500 },
  { description: "airbag warning light", cost: 1500 },
  { description: "fuel filter replacement", cost: 350 },
  { description: "serpentine belt failure", cost: 500 },
  { description: "timing chain issue", cost: 1200 },
  { description: "wheel alignment issues", cost: 400 },
  { description: "flat battery", cost: 350 },
  { description: "smoke from exhaust", cost: 800 },
  { description: "brake pads squealing", cost: 200 },
  { description: "engine losing power", cost: 600 },
  { description: "gearbox issues", cost: 1200 },
  { description: "car pulling to one side", cost: 350 },
  { description: "car vibrations at high speed", cost: 450 },
  { description: "broken window regulator", cost: 500 },
  { description: "car exhaust system repair", cost: 900 },
  { description: "car battery replacement", cost: 500 },
  { description: "oil pressure light", cost: 600 },
  { description: "broken side mirror", cost: 250 },
  { description: "power window failure", cost: 350 },
  { description: "frozen windshield", cost: 400 },
  { description: "steering wheel vibration", cost: 450 },
  { description: "strut replacement", cost: 700 },
  { description: "burning rubber smell", cost: 400 },
  { description: "low tire pressure", cost: 100 },
  { description: "rust on car frame", cost: 1000 },
  { description: "car making whining noise", cost: 500 },
  { description: "engine misfire at idle", cost: 800 },
  { description: "car stalling at stop", cost: 600 },
  { description: "hissing sound from engine", cost: 550 },
  { description: "low brake fluid warning", cost: 300 },
  { description: "bad wheel alignment", cost: 400 },
  { description: "coolant temperature sensor failure", cost: 500 },
  { description: "poor acceleration", cost: 700 },
  { description: "engine stuttering", cost: 600 },
  { description: "differential issues", cost: 1000 },
  { description: "car jerking during acceleration", cost: 600 },
  { description: "broken exhaust manifold", cost: 800 },
  { description: "brake caliper sticking", cost: 600 },
  { description: "bad motor mounts", cost: 700 },
  { description: "clutch pedal vibration", cost: 650 },
  { description: "battery light on dashboard", cost: 450 },
  { description: "vehicle rolling while parked", cost: 300 },
  { description: "engine not turning over", cost: 600 },
  { description: "burnt clutch", cost: 800 },
  { description: "engine warning light", cost: 500 },
  { description: "rough idle", cost: 500 },
  { description: "car hesitating to start", cost: 400 },
  { description: "power lock failure", cost: 250 },
  { description: "car struggling to shift gears", cost: 700 },
  { description: "car backfiring", cost: 600 },
  { description: "broken fog lights", cost: 200 },
  { description: "cracked windshield", cost: 1000 },
  { description: "broken ignition switch", cost: 500 },
  { description: "transmission slipping", cost: 1200 },
  { description: "car doors not opening", cost: 350 },
  { description: "car stalling when turning", cost: 600 },
  { description: "rust in brake lines", cost: 400 },
  { description: "dirty air filter", cost: 150 },
  { description: "car suspension noise", cost: 500 },
  { description: "cracked engine block", cost: 1500 },
  { description: "engine misfire at startup", cost: 900 },
  { description: "strange sound when braking", cost: 300 },
  { description: "battery acid leak", cost: 300 },
  { description: "low antifreeze level", cost: 250 },
  { description: "defective alternator", cost: 800 },
  { description: "car engine flooding", cost: 700 },
  { description: "failing water pump", cost: 900 },
  { description: "defective oil pump", cost: 800 },
  { description: "broken axle", cost: 1000 },
  { description: "no air conditioning", cost: 500 },
  { description: "no heat in car", cost: 450 },
  { description: "worn tires", cost: 300 },
  { description: "car paint fading", cost: 700 },
  { description: "broken timing chain", cost: 1000 },
  { description: "defective fog lights", cost: 200 },
  { description: "bad differential fluid", cost: 500 },
  { description: "overheating engine", cost: 750 },
  { description: "broken air filter housing", cost: 400 },
  { description: "burnt brake pads", cost: 300 },
  { description: "coolant leak", cost: 600 },
  { description: "cracked radiator", cost: 800 },
  { description: "transmission fluid low", cost: 600 },
  { description: "worn-out tie rods", cost: 400 },
  { description: "bad wheel alignment", cost: 350 },
  { description: "cracked radiator hose", cost: 500 },
  { description: "coolant flush needed", cost: 200 },
  { description: "broken sway bar link", cost: 300 },
  { description: "battery charging issue", cost: 400 },
  { description: "engine light flashing", cost: 500 },
  { description: "broken serpentine belt", cost: 400 },
  { description: "alternator not charging", cost: 500 },
  { description: "failed spark plugs", cost: 350 },
  { description: "dirty injectors", cost: 600 },
  { description: "car stuttering when accelerating", cost: 700 },
  { description: "car shaking when braking", cost: 400 },
  { description: "tire tread wear", cost: 200 },
  { description: "rough shifting", cost: 600 },
  { description: "bad engine compression", cost: 800 },
  { description: "dirty fuel filter", cost: 150 },
  { description: "fuel pressure regulator issues", cost: 450 },
  { description: "car stalls in reverse", cost: 500 },
  { description: "vehicle not accelerating", cost: 600 },
  { description: "tire puncture", cost: 150 },
  { description: "loose timing belt", cost: 700 },
  { description: "smell of burning oil", cost: 500 },
  { description: "engine oil overfill", cost: 300 },
  { description: "sticking throttle", cost: 400 },
  { description: "air conditioning compressor failure", cost: 800 },
  { description: "broken timing belt", cost: 1000 },
  { description: "broken piston", cost: 1200 },
  { description: "exhaust system failure", cost: 1000 },
  { description: "blown fuse", cost: 100 },
  { description: "broken seat belt latch", cost: 250 },
  { description: "overfilled transmission fluid", cost: 400 },
  { description: "power steering fluid leak", cost: 350 },
  { description: "fuel line leaks", cost: 500 },
  { description: "cracked exhaust pipe", cost: 800 },
  { description: "bad transmission mounts", cost: 600 },
  { description: "hard shifting", cost: 700 },
  { description: "vehicle misfires when cold", cost: 600 },
  { description: "steering wheel makes noise", cost: 400 },
  { description: "brake rotor problems", cost: 500 },
  { description: "broken ignition coil", cost: 450 },
  { description: "clutch pedal hard to press", cost: 650 },
  { description: "battery light on dashboard", cost: 400 },
  { description: "vehicle rolling while parked", cost: 300 },
  { description: "engine not turning over", cost: 600 },
  { description: "burnt clutch", cost: 800 },
  { description: "engine warning light", cost: 500 },
  { description: "rough idle", cost: 500 },
  { description: "car hesitating to start", cost: 400 },
  { description: "power lock failure", cost: 250 },
  { description: "car struggling to shift gears", cost: 700 },
  { description: "car backfiring", cost: 600 },
  { description: "broken fog lights", cost: 200 },
  { description: "cracked windshield", cost: 1000 },
  { description: "broken ignition switch", cost: 500 },
  { description: "transmission slipping", cost: 1200 },
  { description: "car doors not opening", cost: 350 },
  { description: "car stalling when turning", cost: 600 },
  { description: "rust in brake lines", cost: 400 },
  { description: "dirty air filter", cost: 150 },
  { description: "car suspension noise", cost: 500 },
  { description: "cracked engine block", cost: 1500 },
  { description: "engine misfire at startup", cost: 900 },
  { description: "strange sound when braking", cost: 300 },
  { description: "battery acid leak", cost: 300 },
  { description: "low antifreeze level", cost: 250 },
  { description: "defective alternator", cost: 800 },
  { description: "car engine flooding", cost: 700 },
  { description: "failing water pump", cost: 900 },
  { description: "defective oil pump", cost: 800 },
  { description: "broken axle", cost: 1000 },
  { description: "no air conditioning", cost: 500 },
  { description: "no heat in car", cost: 450 },
  { description: "worn tires", cost: 300 },
  { description: "car paint fading", cost: 700 },
  { description: "broken timing chain", cost: 1000 },
  { description: "defective fog lights", cost: 200 },
  { description: "bad differential fluid", cost: 500 },
  { description: "overheating engine", cost: 750 },
  { description: "broken air filter housing", cost: 400 },
  { description: "burnt brake pads", cost: 300 },
  { description: "coolant leak", cost: 600 },
  { description: "cracked radiator", cost: 800 },
  { description: "transmission fluid low", cost: 600 },
  { description: "worn-out tie rods", cost: 400 },
  { description: "bad wheel alignment", cost: 350 },
  { description: "cracked radiator hose", cost: 500 },
  { description: "coolant flush needed", cost: 200 },
  { description: "broken sway bar link", cost: 300 },
  { description: "battery charging issue", cost: 400 },
  { description: "engine light flashing", cost: 500 },
  { description: "broken serpentine belt", cost: 400 },
  { description: "alternator not charging", cost: 500 },
  { description: "failed spark plugs", cost: 350 },
  { description: "dirty injectors", cost: 600 },
  { description: "car stuttering when accelerating", cost: 700 },
  { description: "car shaking when braking", cost: 400 },
  { description: "tire tread wear", cost: 200 },
  { description: "rough shifting", cost: 600 },
  { description: "bad engine compression", cost: 800 },
  { description: "dirty fuel filter", cost: 150 },
  { description: "fuel pressure regulator issues", cost: 450 },
  { description: "car stalls in reverse", cost: 500 },
  { description: "vehicle not accelerating", cost: 600 },
  { description: "tire puncture", cost: 150 },
  { description: "loose timing belt", cost: 700 },
  { description: "smell of burning oil", cost: 500 },
  { description: "engine oil overfill", cost: 300 },
  { description: "sticking throttle", cost: 400 },
  { description: "air conditioning compressor failure", cost: 800 },
  { description: "broken timing belt", cost: 1000 },
  { description: "broken piston", cost: 1200 },
  { description: "exhaust system failure", cost: 1000 },
  { description: "blown fuse", cost: 100 },
  { description: "broken seat belt latch", cost: 250 },
  { description: "overfilled transmission fluid", cost: 400 },
  { description: "power steering fluid leak", cost: 350 },
  { description: "fuel line leaks", cost: 500 },
  { description: "cracked exhaust pipe", cost: 800 },
  { description: "bad transmission mounts", cost: 600 },
  { description: "hard shifting", cost: 700 },
  { description: "vehicle misfires when cold", cost: 600 },
  { description: "steering wheel makes noise", cost: 400 },
  { description: "brake rotor problems", cost: 500 },
  { description: "broken ignition coil", cost: 450 },
  { description: "clutch pedal hard to press", cost: 650 },
  { description: "battery light on dashboard", cost: 400 },
  { description: "vehicle rolling while parked", cost: 300 },
  { description: "engine not turning over", cost: 600 },
  { description: "burnt clutch", cost: 800 },
  { description: "engine warning light", cost: 500 },
  { description: "rough idle", cost: 500 },
  { description: "car hesitating to start", cost: 400 },
  { description: "power lock failure", cost: 250 },
  { description: "car struggling to shift gears", cost: 700 },
  { description: "car backfiring", cost: 600 },
  { description: "broken fog lights", cost: 200 },
  { description: "cracked windshield", cost: 1000 },
  { description: "broken ignition switch", cost: 500 },
  { description: "transmission slipping", cost: 1200 },
  { description: "car doors not opening", cost: 350 },
  { description: "car stalling when turning", cost: 600 },
  { description: "rust in brake lines", cost: 400 },
  { description: "dirty air filter", cost: 150 },
  { description: "car suspension noise", cost: 500 },
  { description: "cracked engine block", cost: 1500 },
  { description: "engine misfire at startup", cost: 900 },
  { description: "strange sound when braking", cost: 300 },
  { description: "battery acid leak", cost: 300 },
  { description: "low antifreeze level", cost: 250 },
  { description: "defective alternator", cost: 800 },
  { description: "car engine flooding", cost: 700 },
  { description: "failing water pump", cost: 900 },
  { description: "defective oil pump", cost: 800 },
  { description: "broken axle", cost: 1000 },
  { description: "no air conditioning", cost: 500 },
  { description: "no heat in car", cost: 450 },
  { description: "worn tires", cost: 300 },
  { description: "car paint fading", cost: 700 },
  { description: "broken timing chain", cost: 1000 },
  { description: "defective fog lights", cost: 200 },
  { description: "bad differential fluid", cost: 500 },
  { description: "overheating engine", cost: 750 },
  { description: "broken air filter housing", cost: 400 },
  { description: "burnt brake pads", cost: 300 },
  { description: "coolant leak", cost: 600 },
  { description: "cracked radiator", cost: 800 },
  { description: "transmission fluid low", cost: 600 },
  { description: "worn-out tie rods", cost: 400 },
  { description: "bad wheel alignment", cost: 350 },
  { description: "cracked radiator hose", cost: 500 },
  { description: "coolant flush needed", cost: 200 },
  { description: "broken sway bar link", cost: 300 },
  { description: "battery charging issue", cost: 400 },
  { description: "engine light flashing", cost: 500 },
  { description: "broken serpentine belt", cost: 400 },
  { description: "alternator not charging", cost: 500 },
  { description: "failed spark plugs", cost: 350 },
  { description: "dirty injectors", cost: 600 },
  { description: "car stuttering when accelerating", cost: 700 },
  { description: "car shaking when braking", cost: 400 },
  { description: "tire tread wear", cost: 200 },
  { description: "rough shifting", cost: 600 },
  { description: "bad engine compression", cost: 800 },
  { description: "dirty fuel filter", cost: 150 },
  { description: "fuel pressure regulator issues", cost: 450 },
  { description: "car stalls in reverse", cost: 500 },
  { description: "vehicle not accelerating", cost: 600 },
  { description: "tire puncture", cost: 150 },
  { description: "loose timing belt", cost: 700 },
  { description: "smell of burning oil", cost: 500 },
  { description: "engine oil overfill", cost: 300 },
  { description: "sticking throttle", cost: 400 },
  { description: "air conditioning compressor failure", cost: 800 },
  { description: "broken timing belt", cost: 1000 },
  { description: "broken piston", cost: 1200 },
  { description: "exhaust system failure", cost: 1000 },
  { description: "blown fuse", cost: 100 },
  { description: "broken seat belt latch", cost: 250 },
  { description: "overfilled transmission fluid", cost: 400 },
  { description: "power steering fluid leak", cost: 350 },
  { description: "fuel line leaks", cost: 500 },
  { description: "cracked exhaust pipe", cost: 800 },
  { description: "bad transmission mounts", cost: 600 },
  { description: "hard shifting", cost: 700 },
  { description: "vehicle misfires when cold", cost: 600 },
  { description: "steering wheel makes noise", cost: 400 },
  { description: "brake rotor problems", cost: 500 },
  { description: "broken ignition coil", cost: 450 },
  { description: "clutch pedal hard to press", cost: 650 },
  { description: "battery light on dashboard", cost: 400 },
  { description: "vehicle rolling while parked", cost: 300 },
  { description: "engine not turning over", cost: 600 },
  { description: "burnt clutch", cost: 800 },
  { description: "engine warning light", cost: 500 },
  { description: "rough idle", cost: 500 },
  { description: "car hesitating to start", cost: 400 },
  { description: "power lock failure", cost: 250 },
  { description: "car struggling to shift gears", cost: 700 },
  { description: "car backfiring", cost: 600 },
  { description: "broken fog lights", cost: 200 },
  { description: "cracked windshield", cost: 1000 },
  { description: "broken ignition switch", cost: 500 },
  { description: "transmission slipping", cost: 1200 },
  { description: "car doors not opening", cost: 350 },
  { description: "car stalling when turning", cost: 600 },
  { description: "rust in brake lines", cost: 400 },
  { description: "dirty air filter", cost: 150 },
  { description: "car suspension noise", cost: 500 },
  { description: "cracked engine block", cost: 1500 },
  { description: "engine misfire at startup", cost: 900 },
  { description: "strange sound when braking", cost: 300 },
  { description: "battery acid leak", cost: 300 },
  { description: "low antifreeze level", cost: 250 },
  { description: "defective alternator", cost: 800 },
  { description: "car engine flooding", cost: 700 },
  { description: "failing water pump", cost: 900 },
  { description: "defective oil pump", cost: 800 },
  { description: "broken axle", cost: 1000 },
  { description: "no air conditioning", cost: 500 },
  { description: "no heat in car", cost: 450 },
  { description: "worn tires", cost: 300 },
  { description: "car paint fading", cost: 700 },
  { description: "broken timing chain", cost: 1000 },
  { description: "defective fog lights", cost: 200 },
  { description: "bad differential fluid", cost: 500 },
  { description: "overheating engine", cost: 750 },
  { description: "broken air filter housing", cost: 400 },
  { description: "burnt brake pads", cost: 300 },
  { description: "coolant leak", cost: 600 },
  { description: "cracked radiator", cost: 800 },
  { description: "transmission fluid low", cost: 600 },
  { description: "worn-out tie rods", cost: 400 },
  { description: "bad wheel alignment", cost: 350 },
  { description: "cracked radiator hose", cost: 500 },
  { description: "coolant flush needed", cost: 200 },
  { description: "broken sway bar link", cost: 300 },
  { description: "battery charging issue", cost: 400 },
  { description: "engine light flashing", cost: 500 },
  { description: "broken serpentine belt", cost: 400 },
  { description: "alternator not charging", cost: 500 },
  { description: "failed spark plugs", cost: 350 },
  { description: "dirty injectors", cost: 600 },
  { description: "car stuttering when accelerating", cost: 700 },
  { description: "car shaking when braking", cost: 400 },
  { description: "tire tread wear", cost: 200 },
  { description: "rough shifting", cost: 600 },
  { description: "bad engine compression", cost: 800 },
  { description: "dirty fuel filter", cost: 150 },
  { description: "fuel pressure regulator issues", cost: 450 },
  { description: "car stalls in reverse", cost: 500 },
  { description: "vehicle not accelerating", cost: 600 },
  { description: "tire puncture", cost: 150 },
  { description: "loose timing belt", cost: 700 },
  { description: "smell of burning oil", cost: 500 },
  { description: "engine oil overfill", cost: 300 },
  { description: "sticking throttle", cost: 400 },
  { description: "air conditioning compressor failure", cost: 800 },
  { description: "broken timing belt", cost: 1000 },
  { description: "broken piston", cost: 1200 },
  { description: "exhaust system failure", cost: 1000 },
  { description: "blown fuse", cost: 100 },
  { description: "broken seat belt latch", cost: 250 },
  { description: "overfilled transmission fluid", cost: 400 },
  { description: "power steering fluid leak", cost: 350 },
  { description: "fuel line leaks", cost: 500 },
  { description: "cracked exhaust pipe", cost: 800 },
  { description: "bad transmission mounts", cost: 600 },
  { description: "hard shifting", cost: 700 },
  { description: "vehicle misfires when cold", cost: 600 },
  { description: "steering wheel makes noise", cost: 400 },
  { description: "brake rotor problems", cost: 500 },
  { description: "broken ignition coil", cost: 450 },
  { description: "clutch pedal hard to press", cost: 650 },
  { description: "battery light on dashboard", cost: 400 },
  { description: "vehicle rolling while parked", cost: 300 },
  { description: "engine not turning over", cost: 600 },
  { description: "burnt clutch", cost: 800 },
  { description: "engine warning light", cost: 500 },
  { description: "rough idle", cost: 500 },
  { description: "car hesitating to start", cost: 400 },
  { description: "power lock failure", cost: 250 },
  { description: "car struggling to shift gears", cost: 700 },
  { description: "car backfiring", cost: 600 },
  { description: "broken fog lights", cost: 200 },
  { description: "cracked windshield", cost: 1000 },
  { description: "broken ignition switch", cost: 500 },
  { description: "transmission slipping", cost: 1200 },
  { description: "car doors not opening", cost: 350 },
  { description: "car stalling when turning", cost: 600 },
  { description: "rust in brake lines", cost: 400 },
  { description: "dirty air filter", cost: 150 },
  { description: "car suspension noise", cost: 500 },
  { description: "cracked engine block", cost: 1500 },
  { description: "engine misfire at startup", cost: 900 },
  { description: "strange sound when braking", cost: 300 },
  { description: "battery acid leak", cost: 300 },
  { description: "low antifreeze level", cost: 250 },
  { description: "defective alternator", cost: 800 },
  { description: "car engine flooding", cost: 700 },
  { description: "failing water pump", cost: 900 },
  { description: "defective oil pump", cost: 800 },
  { description: "broken axle", cost: 1000 },
  { description: "no air conditioning", cost: 500 },
  { description: "no heat in car", cost: 450 },
  { description: "worn tires", cost: 300 },
  { description: "car paint fading", cost: 700 },
  { description: "broken timing chain", cost: 1000 },
  { description: "defective fog lights", cost: 200 },
  { description: "bad differential fluid", cost: 500 },
  { description: "overheating engine", cost: 750 },
  { description: "broken air filter housing", cost: 400 },
  { description: "burnt brake pads", cost: 300 },
  { description: "coolant leak", cost: 600 },
  { description: "cracked radiator", cost: 800 },
  { description: "transmission fluid low", cost: 600 },
  { description: "worn-out tie rods", cost: 400 },
  { description: "bad wheel alignment", cost: 350 },
  { description: "cracked radiator hose", cost: 500 },
  { description: "coolant flush needed", cost: 200 },
  { description: "broken sway bar link", cost: 300 },
  { description: "battery charging issue", cost: 400 },
  { description: "engine light flashing", cost: 500 },
  { description: "broken serpentine belt", cost: 400 },
  { description: "alternator not charging", cost: 500 },
  { description: "failed spark plugs", cost: 350 },
  { description: "dirty injectors", cost: 600 },
  { description: "car stuttering when accelerating", cost: 700 },
  { description: "car shaking when braking", cost: 400 },
  { description: "tire tread wear", cost: 200 },
  { description: "rough shifting", cost: 600 },
  { description: "bad engine compression", cost: 800 },
  { description: "dirty fuel filter", cost: 150 },
  { description: "fuel pressure regulator issues", cost: 450 },
  { description: "car stalls in reverse", cost: 500 },
  { description: "vehicle not accelerating", cost: 600 },
  { description: "tire puncture", cost: 150 },
  { description: "loose timing belt", cost: 700 },
  { description: "smell of burning oil", cost: 500 },
  { description: "engine oil overfill", cost: 300 },
  { description: "sticking throttle", cost: 400 },
  { description: "air conditioning compressor failure", cost: 800 },
  { description: "broken timing belt", cost: 1000 },
  { description: "broken piston", cost: 1200 },
  { description: "exhaust system failure", cost: 1000 },
  { description: "blown fuse", cost: 100 },
  { description: "broken seat belt latch", cost: 250 },
  { description: "overfilled transmission fluid", cost: 400 },
  { description: "power steering fluid leak", cost: 350 },
  { description: "fuel line leaks", cost: 500 },
  { description: "cracked exhaust pipe", cost: 800 },
  { description: "bad transmission mounts", cost: 600 },
  { description: "hard shifting", cost: 700 },
  { description: "vehicle misfires when cold", cost: 600 },
  { description: "steering wheel makes noise", cost: 400 },
  { description: "brake rotor problems", cost: 500 },
  { description: "broken ignition coil", cost: 450 },
  { description: "clutch pedal hard to press", cost: 650 },
  { description: "battery light on dashboard", cost: 400 },
  { description: "vehicle rolling while parked", cost: 300 },
  { description: "engine not turning over", cost: 600 },
  { description: "burnt clutch", cost: 800 },
  { description: "engine warning light", cost: 500 },
  { description: "rough idle", cost: 500 },
  { description: "car hesitating to start", cost: 400 },
  { description: "power lock failure", cost: 250 },
  { description: "car struggling to shift gears", cost: 700 },
  { description: "car backfiring", cost: 600 },
  { description: "broken fog lights", cost: 200 },
  { description: "cracked windshield", cost: 1000 },
  { description: "broken ignition switch", cost: 500 },
  { description: "transmission slipping", cost: 1200 },
  { description: "car doors not opening", cost: 350 },
  { description: "car stalling when turning", cost: 600 },
  { description: "rust in brake lines", cost: 400 },
  { description: "dirty air filter", cost: 150 },
  { description: "car suspension noise", cost: 500 },
  { description: "cracked engine block", cost: 1500 },
  { description: "engine misfire at startup", cost: 900 },
  { description: "strange sound when braking", cost: 300 },
  { description: "battery acid leak", cost: 300 },
  { description: "low antifreeze level", cost: 250 },
  { description: "defective alternator", cost: 800 },
  { description: "car engine flooding", cost: 700 },
  { description: "failing water pump", cost: 900 },
  { description: "defective oil pump", cost: 800 },
  { description: "broken axle", cost: 1000 },
  { description: "no air conditioning", cost: 500 },
  { description: "no heat in car", cost: 450 },
  { description: "worn tires", cost: 300 },
  { description: "car paint fading", cost: 700 },
  { description: "broken timing chain", cost: 1000 },
  { description: "defective fog lights", cost: 200 },
  { description: "bad differential fluid", cost: 500 },
  { description: "overheating engine", cost: 750 },
  { description: "broken air filter housing", cost: 400 },
  { description: "burnt brake pads", cost: 300 },
  { description: "coolant leak", cost: 600 },
  { description: "cracked radiator", cost: 800 },
  { description: "transmission fluid low", cost: 600 },
  { description: "worn-out tie rods", cost: 400 },
  { description: "bad wheel alignment", cost: 350 },
  { description: "cracked radiator hose", cost: 500 },
  { description: "coolant flush needed", cost: 200 },
  { description: "broken sway bar link", cost: 300 },
  { description: "battery charging issue", cost: 400 },
  { description: "engine light flashing", cost: 500 },
  { description: "broken serpentine belt", cost: 400 },
  { description: "alternator not charging", cost: 500 },
  { description: "failed spark plugs", cost: 350 },
  { description: "dirty injectors", cost: 600 },
  { description: "car stuttering when accelerating", cost: 700 },
  { description: "car shaking when braking", cost: 400 },
  { description: "tire tread wear", cost: 200 },
  { description: "rough shifting", cost: 600 },
  { description: "bad engine compression", cost: 800 },
  { description: "dirty fuel filter", cost: 150 },
  { description: "fuel pressure regulator issues", cost: 450 },
  { description: "car stalls in reverse", cost: 500 },
  { description: "vehicle not accelerating", cost: 600 },
  { description: "tire puncture", cost: 150 },
  { description: "loose timing belt", cost: 700 },
  { description: "smell of burning oil", cost: 500 },
  { description: "engine oil overfill", cost: 300 },
  { description: "sticking throttle", cost: 400 },
  { description: "air conditioning compressor failure", cost: 800 },
  { description: "broken timing belt", cost: 1000 },
  { description: "broken piston", cost: 1200 },
  { description: "exhaust system failure", cost: 1000 },
  { description: "blown fuse", cost: 100 },
  { description: "broken seat belt latch", cost: 250 },
  { description: "overfilled transmission fluid", cost: 400 },
  { description: "power steering fluid leak", cost: 350 },
  { description: "fuel line leaks", cost: 500 },
  { description: "cracked exhaust pipe", cost: 800 },
  { description: "bad transmission mounts", cost: 600 },
  { description: "hard shifting", cost: 700 },
  { description: "vehicle misfires when cold", cost: 600 },
  { description: "steering wheel makes noise", cost: 400 },
  { description: "brake rotor problems", cost: 500 },
  { description: "broken ignition coil", cost: 450 },
  { description: "clutch pedal hard to press", cost: 650 },
  { description: "battery light on dashboard", cost: 400 },
  { description: "vehicle rolling while parked", cost: 300 },
  { description: "engine not turning over", cost: 600 },
  { description: "burnt clutch", cost: 800 },
  { description: "engine warning light", cost: 500 },
  { description: "rough idle", cost: 500 },
  { description: "car hesitating to start", cost: 400 },
  { description: "power lock failure", cost: 250 },
  { description: "car struggling to shift gears", cost: 700 },
  { description: "car backfiring", cost: 600 },
  { description: "broken fog lights", cost: 200 },
  { description: "cracked windshield", cost: 1000 },
  { description: "broken ignition switch", cost: 500 },
  { description: "transmission slipping", cost: 1200 },
  { description: "car doors not opening", cost: 350 },
  { description: "car stalling when turning", cost: 600 },
  { description: "rust in brake lines", cost: 400 },
  { description: "dirty air filter", cost: 150 },
  { description: "car suspension noise", cost: 500 },
  { description: "cracked engine block", cost: 1500 },
  { description: "engine misfire at startup", cost: 900 },
  { description: "strange sound when braking", cost: 300 },
  { description: "battery acid leak", cost: 300 },
  { description: "low antifreeze level", cost: 250 },
  { description: "defective alternator", cost: 800 },
  { description: "car engine flooding", cost: 700 },
  { description: "failing water pump", cost: 900 },
  { description: "defective oil pump", cost: 800 },
  { description: "broken axle", cost: 1000 },
  { description: "no air conditioning", cost: 500 },
  { description: "no heat in car", cost: 450 },
  { description: "worn tires", cost: 300 },
  { description: "car paint fading", cost: 700 },
  { description: "broken timing chain", cost: 1000 },
  { description: "defective fog lights", cost: 200 },
  { description: "bad differential fluid", cost: 500 },
  { description: "overheating engine", cost: 750 },
  { description: "broken air filter housing", cost: 400 },
  { description: "burnt brake pads", cost: 300 },
  { description: "coolant leak", cost: 600 },
  { description: "cracked radiator", cost: 800 },
  { description: "transmission fluid low", cost: 600 },
  { description: "worn-out tie rods", cost: 400 },
  { description: "bad wheel alignment", cost: 350 },
  { description: "cracked radiator hose", cost: 500 },
  { description: "coolant flush needed", cost: 200 },
  { description: "broken sway bar link", cost: 300 },
  { description: "battery charging issue", cost: 400 },
  { description: "engine light flashing", cost: 500 },
  { description: "broken serpentine belt", cost: 400 },
  { description: "alternator not charging", cost: 500 },
  { description: "failed spark plugs", cost: 350 },
  { description: "dirty injectors", cost: 600 },
  { description: "car stuttering when accelerating", cost: 700 },
  { description: "car shaking when braking", cost: 400 },
  { description: "tire tread wear", cost: 200 },
  { description: "rough shifting", cost: 600 },
  { description: "bad engine compression", cost: 800 },
  { description: "dirty fuel filter", cost: 150 },
  { description: "fuel pressure regulator issues", cost: 450 },
  { description: "car stalls in reverse", cost: 500 },
  { description: "vehicle not accelerating", cost: 600 },
  { description: "tire puncture", cost: 150 },
  { description: "loose timing belt", cost: 700 },
  { description: "smell of burning oil", cost: 500 },
  { description: "engine oil overfill", cost: 300 },
  { description: "sticking throttle", cost: 400 },
  { description: "air conditioning compressor failure", cost: 800 },
  { description: "broken timing belt", cost: 1000 },
  { description: "broken piston", cost: 1200 },
  { description: "exhaust system failure", cost: 1000 },
  { description: "blown fuse", cost: 100 },
  { description: "broken seat belt latch", cost: 250 },
  { description: "overfilled transmission fluid", cost: 400 },
  { description: "power steering fluid leak", cost: 350 },
  { description: "fuel line leaks", cost: 500 },
  { description: "cracked exhaust pipe", cost: 800 },
  { description: "bad transmission mounts", cost: 600 },
  { description: "hard shifting", cost: 700 },
  { description: "vehicle misfires when cold", cost: 600 },
  { description: "steering wheel makes noise", cost: 400 },
  { description: "brake rotor problems", cost: 500 },
  { description: "broken ignition coil", cost: 450 },
  { description: "clutch pedal hard to press", cost: 650 },
  { description: "battery light on dashboard", cost: 400 },
  { description: "vehicle rolling while parked", cost: 300 },
  { description: "engine not turning over", cost: 600 },
  { description: "burnt clutch", cost: 800 },
  { description: "engine warning light", cost: 500 },
  { description: "rough idle", cost: 500 },
  { description: "car hesitating to start", cost: 400 },
  { description: "power lock failure", cost: 250 },
  { description: "car struggling to shift gears", cost: 700 },
  { description: "car backfiring", cost: 600 },
  { description: "broken fog lights", cost: 200 },
  { description: "cracked windshield", cost: 1000 },
  { description: "broken ignition switch", cost: 500 },
  { description: "transmission slipping", cost: 1200 },
  { description: "car doors not opening", cost: 350 },
  { description: "car stalling when turning", cost: 600 },
  { description: "rust in brake lines", cost: 400 },
  { description: "dirty air filter", cost: 150 },
  { description: "car suspension noise", cost: 500 },
  { description: "cracked engine block", cost: 1500 },
  { description: "engine misfire at startup", cost: 900 },
  { description: "strange sound when braking", cost: 300 },
  { description: "battery acid leak", cost: 300 },
  { description: "low antifreeze level", cost: 250 },
  { description: "defective alternator", cost: 800 },
  { description: "car engine flooding", cost: 700 },
  { description: "failing water pump", cost: 900 },
  { description: "defective oil pump", cost: 800 },
  { description: "broken axle", cost: 1000 },
  { description: "no air conditioning", cost: 500 },
  { description: "no heat in car", cost: 450 },
  { description: "worn tires", cost: 300 },
  { description: "car paint fading", cost: 700 },
  { description: "broken timing chain", cost: 1000 },
  { description: "defective fog lights", cost: 200 },
  { description: "bad differential fluid", cost: 500 },
  { description: "overheating engine", cost: 750 },
  { description: "broken air filter housing", cost: 400 },
  { description: "burnt brake pads", cost: 300 },
  { description: "coolant leak", cost: 600 },
  { description: "cracked radiator", cost: 800 },
  { description: "transmission fluid low", cost: 600 },
  { description: "worn-out tie rods", cost: 400 },
  { description: "bad wheel alignment", cost: 350 },
  { description: "cracked radiator hose", cost: 500 },
  { description: "coolant flush needed", cost: 200 },
  { description: "broken sway bar link", cost: 300 },
  { description: "battery charging issue", cost: 400 },
  { description: "engine light flashing", cost: 500 },
  { description: "broken serpentine belt", cost: 400 },
  { description: "alternator not charging", cost: 500 },
  { description: "failed spark plugs", cost: 350 },
  { description: "dirty injectors", cost: 600 },
  { description: "car stuttering when accelerating", cost: 700 },
  { description: "car shaking when braking", cost: 400 },
  { description: "tire tread wear", cost: 200 },
  { description: "rough shifting", cost: 600 },
  { description: "bad engine compression", cost: 800 },
  { description: "dirty fuel filter", cost: 150 },
  { description: "fuel pressure regulator issues", cost: 450 },
  { description: "car stalls in reverse", cost: 500 },
  { description: "vehicle not accelerating", cost: 600 },
  { description: "tire puncture", cost: 150 },
  { description: "loose timing belt", cost: 700 },
  { description: "smell of burning oil", cost: 500 },
  { description: "engine oil overfill", cost: 300 },
  { description: "sticking throttle", cost: 400 },
  { description: "air conditioning compressor failure", cost: 800 },
  { description: "broken timing belt", cost: 1000 },
  { description: "broken piston", cost: 1200 },
  { description: "exhaust system failure", cost: 1000 },
  { description: "blown fuse", cost: 100 },
  { description: "broken seat belt latch", cost: 250 },
  { description: "overfilled transmission fluid", cost: 400 },
  { description: "power steering fluid leak", cost: 350 },
  { description: "fuel line leaks", cost: 500 },
  { description: "cracked exhaust pipe", cost: 800 },
  { description: "bad transmission mounts", cost: 600 },
  { description: "hard shifting", cost: 700 },
  { description: "vehicle misfires when cold", cost: 600 },
  { description: "steering wheel makes noise", cost: 400 },
  { description: "brake rotor problems", cost: 500 },
  { description: "broken ignition coil", cost: 450 },
  { description: "clutch pedal hard to press", cost: 650 },
  { description: "battery light on dashboard", cost: 400 },
  { description: "vehicle rolling while parked", cost: 300 },
  { description: "engine not turning over", cost: 600 },
  { description: "burnt clutch", cost: 800 },
  { description: "engine warning light", cost: 500 },
  { description: "rough idle", cost: 500 },
  { description: "car hesitating to start", cost: 400 },
  { description: "power lock failure", cost: 250 },
  { description: "car struggling to shift gears", cost: 700 },
  { description: "car backfiring", cost: 600 },
  { description: "broken fog lights", cost: 200 },
  { description: "cracked windshield", cost: 1000 },
  { description: "broken ignition switch", cost: 500 },
  { description: "transmission slipping", cost: 1200 },
  { description: "car doors not opening", cost: 350 },
  { description: "car stalling when turning", cost: 600 },
  { description: "rust in brake lines", cost: 400 },
  { description: "dirty air filter", cost: 150 },
  { description: "car suspension noise", cost: 500 },
  { description: "cracked engine block", cost: 1500 },
  { description: "engine misfire at startup", cost: 900 },
  { description: "strange sound when braking", cost: 300 },
  { description: "battery acid leak", cost: 300 },
  { description: "low antifreeze level", cost: 250 },
  { description: "defective alternator", cost: 800 },
  { description: "car engine flooding", cost: 700 },
  { description: "failing water pump", cost: 900 },
  { description: "defective oil pump", cost: 800 },
  { description: "broken axle", cost: 1000 },
  { description: "no air conditioning", cost: 500 },
  { description: "no heat in car", cost: 450 },
  { description: "worn tires", cost: 300 },
  { description: "car paint fading", cost: 700 },
  { description: "broken timing chain", cost: 1000 },
  { description: "defective fog lights", cost: 200 },
  { description: "bad differential fluid", cost: 500 },
  { description: "overheating engine", cost: 750 },
  { description: "broken air filter housing", cost: 400 },
  { description: "burnt brake pads", cost: 300 },
  { description: "coolant leak", cost: 600 },
  { description: "cracked radiator", cost: 800 },
  { description: "transmission fluid low", cost: 600 },
  { description: "worn-out tie rods", cost: 400 },
  { description: "bad wheel alignment", cost: 350 },
  { description: "cracked radiator hose", cost: 500 },
  { description: "coolant flush needed", cost: 200 },
  { description: "broken sway bar link", cost: 300 },
  { description: "battery charging issue", cost: 400 },
  { description: "engine light flashing", cost: 500 },
  { description: "broken serpentine belt", cost: 400 },
  { description: "alternator not charging", cost: 500 },
  { description: "failed spark plugs", cost: 350 },
  { description: "dirty injectors", cost: 600 },
  { description: "car stuttering when accelerating", cost: 700 },
  { description: "car shaking when braking", cost: 400 },
  { description: "tire tread wear", cost: 200 },
  { description: "rough shifting", cost: 600 },
  { description: "bad engine compression", cost: 800 },
  { description: "dirty fuel filter", cost: 150 },
  { description: "fuel pressure regulator issues", cost: 450 },
  { description: "car stalls in reverse", cost: 500 },
  { description: "vehicle not accelerating", cost: 600 },
  { description: "tire puncture", cost: 150 },
  { description: "loose timing belt", cost: 700 },
  { description: "smell of burning oil", cost: 500 },
  { description: "engine oil overfill", cost: 300 },
  { description: "sticking throttle", cost: 400 },
  { description: "air conditioning compressor failure", cost: 800 },
  { description: "broken timing belt", cost: 1000 },
  { description: "broken piston", cost: 1200 },
  { description: "exhaust system failure", cost: 1000 },
  { description: "blown fuse", cost: 100 },
  { description: "broken seat belt latch", cost: 250 },
  { description: "overfilled transmission fluid", cost: 400 },
  { description: "power steering fluid leak", cost: 350 },
  { description: "fuel line leaks", cost: 500 },
  { description: "cracked exhaust pipe", cost: 800 },
  { description: "bad transmission mounts", cost: 600 },
  { description: "hard shifting", cost: 700 },
  { description: "vehicle misfires when cold", cost: 600 },
  { description: "steering wheel makes noise", cost: 400 },
  { description: "brake rotor problems", cost: 500 },
  { description: "broken ignition coil", cost: 450 },
  { description: "clutch pedal hard to press", cost: 650 },
  { description: "battery light on dashboard", cost: 400 },
  { description: "vehicle rolling while parked", cost: 300 },
  { description: "engine not turning over", cost: 600 },
  { description: "burnt clutch", cost: 800 },
  { description: "engine warning light", cost: 500 },
  { description: "rough idle", cost: 500 },
  { description: "car hesitating to start", cost: 400 },
  { description: "power lock failure", cost: 250 },
  { description: "car struggling to shift gears", cost: 700 },
  { description: "car backfiring", cost: 600 },
  { description: "broken fog lights", cost: 200 },
  { description: "cracked windshield", cost: 1000 },
  { description: "broken ignition switch", cost: 500 },
  { description: "transmission slipping", cost: 1200 },
  { description: "car doors not opening", cost: 350 },
  { description: "car stalling when turning", cost: 600 },
  { description: "rust in brake lines", cost: 400 },
  { description: "dirty air filter", cost: 150 },
  { description: "car suspension noise", cost: 500 },
  { description: "cracked engine block", cost: 1500 },
  { description: "engine misfire at startup", cost: 900 },
  { description: "strange sound when braking", cost: 300 },
  { description: "battery acid leak", cost: 300 },
  { description: "low antifreeze level", cost: 250 },
  { description: "defective alternator", cost: 800 },
  { description: "car engine flooding", cost: 700 },
  { description: "failing water pump", cost: 900 },
  { description: "defective oil pump", cost: 800 },
  { description: "broken axle", cost: 1000 },
  { description: "no air conditioning", cost: 500 },
  { description: "no heat in car", cost: 450 },
  { description: "worn tires", cost: 300 },
  { description: "car paint fading", cost: 700 },
  { description: "broken timing chain", cost: 1000 },
  { description: "defective fog lights", cost: 200 },
  { description: "bad differential fluid", cost: 500 },
  { description: "overheating engine", cost: 750 },
  { description: "broken air filter housing", cost: 400 },
  { description: "burnt brake pads", cost: 300 },
  { description: "coolant leak", cost: 600 },
  { description: "cracked radiator", cost: 800 },
  { description: "transmission fluid low", cost: 600 },
  { description: "worn-out tie rods", cost: 400 },
];

module.exports = {
  getAllProblems: () => problemDescriptions,
  getProblemByDescription: (description) => {
    return problemDescriptions.find((p) => p.description === description);
  },
};
